- name: 收集已经安装的软件包
  package_facts:
    manager: auto

- block:
    - name: 已经安装Docker
      shell: 'yum remove docker* docker-ce|find / -iname docker|xargs rm -rf '
  when: "'docker' in ansible_facts.packages"
  

- block:
    - name: 准备docker相关目录
      file: name={{ item }} state=directory
      with_items:
      - "/usr/local/bin"
      - "/etc/docker"
      - "/etc/docker/storage"
      - "/etc/bash_completion.d"
    
    - name: copy docker 二进制文件
      copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - containerd-shim-runc-v2
      - docker-init
      - runc
      - ctr
      - docker
      - dockerd
      - docker-proxy
    
    - name: docker命令自动补全
      copy: src=docker dest=/etc/bash_completion.d/docker mode=0644
    
    - name: docker国内镜像加速
      template: src=daemon.json.j2 dest=/etc/docker/daemon.json
    
    - name: flush-iptables
      shell: "iptables -P INPUT ACCEPT \
            && iptables -P FORWARD ACCEPT \
            && iptables -P OUTPUT ACCEPT \
            && iptables -F && iptables -X \
            && iptables -F -t nat && iptables -X -t nat \
            && iptables -F -t raw && iptables -X -t raw \
            && iptables -F -t mangle && iptables -X -t mangle"
    
    - name: 创建docker的systemd unit文件
      template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
    
    - name: 开机启用docker 服务
      shell: systemctl enable docker
      ignore_errors: true
    
    - name: 开启docker 服务
      shell: systemctl daemon-reload && systemctl restart docker

    - name: 等待docker服务运行
      shell: "systemctl is-active docker.service"
      register: docker_status
      until: '"active" in docker_status.stdout'
      retries: 8
      delay: 2
  
  
