- name: 检查是否安装Containerd
  shell: 'systemctl is-active containerd || echo "NoFound"'
  register: containerd_svc

- block:
    - name: 创建Containerd所需目录
      file: name={{ item }} state=directory
      with_items: 
      - "/etc/containerd"
      - "/etc/containerd/img"
      - "/usr/local/bin"
      ignore_errors: true

    - name: 加载内核模块Overlay
      modprobe: name=overlay  state=present

    - name: 拷贝Containerd二进制文件
      copy: src={{ item }} dest=/usr/local/bin/{{ item }} mode=0755
      with_items:
      - containerd
      - containerd-shim
      - containerd-shim-runc-v1
      - containerd-shim-runc-v2
      - containerd-stress
      - crictl
      - ctr
      - runc
      tags: containerd_upgrade

    - name: 创建Containerd配置文件
      template: src=config.toml.j2 dest=/etc/containerd/config.toml
      tags: upgrade

    - name: 创建systemd unit文件
      template: src=containerd.service.j2 dest=/etc/systemd/system/containerd.service
      tags: upgrade

    - name: 创建 crictl 配置
      template: src=crictl.yaml.j2 dest=/etc/crictl.yaml

    - name: 开机启用 containerd 服务
      shell: systemctl enable containerd
      ignore_errors: true

    - name: 开启 containerd 服务
      shell: systemctl daemon-reload && systemctl restart containerd
      tags: upgrade

    - name: 轮询等待containerd服务运行
      shell: "systemctl is-active containerd.service"
      register: containerd_status
      until: '"active" in containerd_status.stdout'
      retries: 8
      delay: 2
      tags: upgrade
  when: "'NoFound' in containerd_svc.stdout"
